spring.application.name=photoBooth
server.port=9999
logging.level.root=INFO
logging.level.com.example.photoBooth=INFO
logging.level.org.springframework.security=DEBUG
spring.security.user.name=user
spring.security.user.password=password