spring.application.name=photoBooth
server.port=9999
logging.level.root=INFO
logging.level.com.example.photoBooth=INFO
logging.level.org.springframework.security=DEBUG
spring.security.user.name=user
spring.security.user.password=password

spring.datasource.url=jdbc:postgresql://localhost:5432/photobooth
spring.datasource.username=photobooth
spring.datasource.password=photobooth
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true