CREATE TABLE album (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_name   VARCHAR(255),
    city_name    VARCHAR(255),
    country_name VARCHAR(255)
);

CREATE TABLE image (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img      VARCHAR(255),
    album_id INTEGER,
    CONSTRAINT fk_image_album FOREIGN KEY (album_id) REFERENCES album (id)
);