-- Wipe existing dev data: album.owner_id is about to become NOT NULL,
-- and no existing test album has a real owner to backfill.
TRUNCATE TABLE image, album;

-- Roles: a small, fixed reference table. Seeded immediately since
-- registration needs ROLE_USER to exist from the start.
CREATE TABLE role (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO role (name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');

-- Users
CREATE TABLE app_user (
    id                  UUID PRIMARY KEY,
    username            VARCHAR(255) NOT NULL UNIQUE,
    password            VARCHAR(255) NOT NULL,
    password_changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    enabled             BOOLEAN NOT NULL
);

-- User <-> Role, a pure many-to-many join table (no surrogate key needed)
CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES role (id)
);

-- Album ownership
ALTER TABLE album ADD COLUMN owner_id UUID NOT NULL;
ALTER TABLE album ADD CONSTRAINT fk_album_owner FOREIGN KEY (owner_id) REFERENCES app_user (id);

CREATE INDEX idx_album_owner_id ON album (owner_id);